### PR TITLE
Add symcache tests and examples [WIP]

### PR DESCRIPTION
**Pull request by jan-auer**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
We should try to get this merged.

**Comment by jan-auer** [comment]
Will do so on Monday. Generating basic tests is not too hard, I have some more approaches that I can implement here. Do you have some special cases that you ran into in the last weeks?

**Comment by mitsuhiko** [comment]
One issue i just fixed was that we accidentally missed the first line record in a function :)

**Comment by jan-auer** [comment]
Once #6 has landed, I would like to revisit this pull request. Still not sure if it's better to generate debug data and crashes on-the-fly or just check them in as in `py/tests`

**Comment by mitsuhiko** [comment]
plop

**Pull request closed without merging**
