### PR TITLE
fix(sourcebundles): Skip invalid sources

### LINKED ISSUE #860: Uploading debug information files fails in v2.33.1
### CLI Version

2.33.1

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [x] Windows (x86_64)

### Operating System Version

Windows Server

### Link to reproduction repository

https://github.com/p0358/black_market_edition/actions/runs/10231364720/job/28307610591

### CLI Command

sentry-cli upload-dif --include-sources $files_to_upload

### Exact Reproduction Steps

Compile a C++ app and:
```ps
          $files_to_upload = Get-ChildItem -Path build\bin -Recurse -Include ("*.pdb", "*.dll", "*.exe")
          echo "Files to upload:" $files_to_upload
          sentry-cli upload-dif --include-sources $files_to_upload
```

### Expected Results

It should work like it did before. In v2.33.1 with PR getsentry/sentry-cli#2109 the issue getsentry/sentry-cli#2107 was reintroduced, which was previously fixed by getsentry/sentry-cli#2108, which had version v2.32.2. It looks like in both this repo and https://github.com/getsentry/symbolic/pull/816 somebody added a check for input files being UTF-8, seemingly forgetting that JavaScript is not the only language and that native apps with symbol files exist??? Barely any reasoning if at all was provided in the linked PRs as to what originally prompted such a check to be coded to begin with.

Proof for people with internal access at Sentry that it worked with symbolification and showing up source code and correct line of code: https://black-market-edition.sentry.io/issues/5651900111/?project=5545628

### Actual Results

It fails:
```
Run $files_to_upload = Get-ChildItem -Path build\bin -Recurse -Include ("*.pdb", "*.dll", "*.exe")
Files to upload:
    Directory: D:\a\black_market_edition\black_market_edition\build\bin\x64-Staging
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            8/3/2024 11:08 PM        1876480 bme.dll
-a---            8/3/2024 11:08 PM       20779008 bme.pdb
-a---            8/3/2024 11:07 PM         389120 curl.pdb
-a---            8/3/2024 11:07 PM         946176 discord-rpc.pdb
-a---            8/3/2024 11:07 PM         921600 imgui.pdb
-a---            8/3/2024 11:07 PM         183808 launcher.dll
-a---            8/3/2024 11:07 PM        4837376 launcher.pdb
-a---            8/3/2024 11:07 PM         110592 minhook.pdb
-a---            8/3/2024 11:07 PM         176128 nghttp2.pdb
-a---            8/3/2024 11:07 PM        3534848 spdlog.pdb
-a---            8/3/2024 11:07 PM         547328 Titanfall_alt.exe
-a---            8/3/2024 11:07 PM        4419584 Titanfall_alt.pdb
> Found 6 debug information files
error: file could not be read as UTF-8
  caused by: stream did not contain valid UTF-8
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
Error: Process completed with exit code 1.
```

### Logs

There wouldn't be any extra  info in debug log according to what I saw in other issues

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
Fixes #860

### CODE REVIEW

**Comment by p0358** [comment]
Hmm, it would be nice to note the file being skipped at least in the debug logs. I fear I might have some leftover source files that might actually have some singular improper UTF-8 inserted due to copy-paste, as was the case a single time in the past, and then such a .cpp file would be silently skipped without any way of ever knowing...

**Comment by Swatinem** [comment]
Unfortunately, we do not really have a good story around surfacing these errors as warnings, but I do agree that silently skipping these files might not be the best solution here.

**Comment by p0358** [comment]
I can actually imagine why putting them as warnings wouldn't be desirable (potential huge spam). But in opt-in debug-level log why not? I'm not sure if there's really any other convenient way to figure out which files are causing these problems, and I'm curious if it just picks up something else, or if there's some problem in one of actual source code files (we had a situation like that before where compiler would yield a warning about invalid UTF-8 sequence copy-pasted somewhere, which is why I'm so curious...).

**Comment by szokeasaurusrex** [comment]
@loewenheim @Swatinem would it perhaps be possible to return a list of all the files we had to skip over due to encoding failures? Then, the calling code (in this case, Sentry CLI) could decide how to handle these (warn, error, etc).

**Comment by Swatinem** [comment]
I think that sounds reasonable, but I believe that also requires breaking changes in symbolic.

**Comment by szokeasaurusrex** [comment]
Yeah, that was my concern. We could always introduce a new variant  of `write_object_with_filter` with a change signature that supports such a return value, then keep the original `write_object_with_filter` around with its current signature for backwards compatibility. Not sure this is the best path though

**Comment by loewenheim** [comment]
I would go with that option then, yeah.

**Review by loewenheim — APPROVED** [review]

**Comment by szokeasaurusrex** [comment]
@p0358 we are going to work on getting this logging to work in a separate issue: #863

**Pull request merged**
