### PR TITLE
fix: Using Hermes SourceMaps with non-hermes stackframes

### PR DESCRIPTION
**Pull request by Swatinem**
This was a misunderstanding on my part. The `SourceMapHermes` actually is not specific to Hermes at all. It’s just a SourceMap with additional scoping information. So it can be used without Hermes.

### CODE REVIEW

**Comment by HazAT** [comment]
This implies a sentry and sentry-cli release?
Correct?

**Comment by Swatinem** [comment]
@HazAT  just `sentry`, the CLI is not affected.

**Comment by HazAT** [comment]
Sweet

**Comment by HazAT** [comment]
:shipit: cc @Swatinem

**Pull request merged**
