### PR TITLE
ref: Work around gimli re-parsing Abbreviations

### PR DESCRIPTION
**Pull request by Swatinem**
Abbreviations in the debug_abbrev section can be, and often are, shared between compilation units. However, the upstream `gimli::Unit::new` eagerly parses and allocates `Abbreviations` for each `Unit`.

We have a pathological case where an extremely large 5.5G DWARF file with ~280k compilation units and ~1500 Abbreviations is taking a very long time to process and is holding on to an unreasonable amount of memory while doing so.
Profiling suggests a majority of time and memory is spent parsing and dropping these Abbreviations.

This workaround copies the `gimli::Unit::new` code to avoid parsing `Abbreviations` at offset 0. In the pathological case mentioned above, *all* the compilation units share the same list of `Abbreviations` at offset 0.

Runtime of symcache conversion for the mentioned pathological case goes from 13 minutes down to slightly over 1 minute, and peak memory usage from 18G down to 8G. Not great, not terrible, but a huge improvement nonetheless.

### CODE REVIEW

**Comment by loewenheim** [comment]
Should this be "properly" fixed upstream?

**Comment by Swatinem** [comment]
Ideally yes, though its not yet clear what would be the best way to go about it. I filed https://github.com/gimli-rs/gimli/issues/626 upstream.

**Comment by Swatinem** [comment]
I just checked with an `electron.debug` and this workaround does not help there. The electron DWARF seems to rather have multiple `debug_abbrev` lists (one per compilation unit perhaps?)

**Comment by loewenheim** [comment]
Do we need to improve performance for `electron.debug` or were you just checking if this change incidentally helps in that case?

**Comment by Swatinem** [comment]
Yes, I was just checking another random "huge ass" debug file. Seems like it has a different DWARF structure internally and does not deduplicate `Abbreviations` into a single huge table, but instead has many smaller tables (but with duplicated entries).
This workaround does not help that usecase.

**Review by loewenheim — APPROVED** [review]

**Pull request merged**
