### PR TITLE
ref: Remove minidump_stackwalk utility

### PR DESCRIPTION
**Pull request by loewenheim**
This removes `minidump_stackwalk` from the examples, since with the upcoming removal of `symbolic-minidump` it will be obsolete anyway and in the meantime it's one less file I have to worry about during refactorings.

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
I’m wondering if we should eventually offer something like this again in the future. So we can more easily run/debug minidumps locally, vs spinning up a complete symbolicator instance and running minidumps through there.

**Comment by mitsuhiko** [comment]
The removal definitely makes me sadface. I declare myself as a common user of this.

**Comment by loewenheim** [comment]
> The removal definitely makes me sadface. I declare myself as a common user of this.

@jan-auer has expressed the same sentiment. We're going to have to think about how we can keep this around.

**Comment by loewenheim** [comment]
See https://github.com/getsentry/symbolic/pull/561 for a proposed alternative to removing this.

**Pull request closed without merging**
