### PR TITLE
fix: Make the Win-x64 CFI code more faithful

### LINKED ISSUE #546: symbolic-minidump mishandling UnwindOperation::SetFPRegister?
Mozilla has some inline asm with some handwritten unwind tables, but it seems like dumpsyms isn't handling this line properly: https://searchfox.org/mozilla-central/rev/2c4522f76b23b024d9f29e140d41042853874c07/xpcom/reflect/xptcall/md/win32/xptcinvoke_asm_x86_64.asm#27

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1765243

### PR DESCRIPTION
**Pull request by Swatinem**
This is trying to fix #546 by more faithfully implementing Win-x64 unwinding, specifically:
It restores all the registers that were saved, and adds support for FP-based unwinding.

I’m still struggling to make this code work correctly with `RtlDispatchException` which we somehow still can’t unwind through.

### CODE REVIEW

**Comment by gabrielesvelto** [comment]
> I’m wondering what the unwind codes for `KiUserExceptionDispatch` are…

That's a very good point. Before your patch the directives for `KiUserExceptionDispatch` were the following:
```
STACK CFI INIT a0bd0 5c .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI a0bd0 .cfa: $rsp 1472 + $rsp: .cfa 24 - ^ .ra: .cfa 48 - ^
```
With your patch applied they become:
```
STACK CFI INIT a0bd0 5c .cfa: $rsp 1472 + $rsp: .cfa 24 - ^ .ra: cfa 48 - ^ $rbx: .cfa 1328 - ^ $rbp: .cfa 1312 - ^ $rsi: .cfa 1304 - ^ $rdi: .cfa 1296 - ^ $r12: .cfa 1256 - ^ $r13: .cfa 1248 - ^ $r14: .cfa 1240 - ^ $r15: .cfa 1232 - ^
```
So I had an idea, and I copy-pasted the old CFI directives for `KiUserExceptionDispatch` into the .sym file generated with your patch applied and here's the stack trace I got:
```
 0  ntdll.dll!LdrpICallHandler + 0xf
    Found by: given as instruction pointer in context
 1  ntdll.dll!RtlpExecuteHandlerForException + 0xe
    Found by: call frame info
 2  ntdll.dll!RtlDispatchException + 0x243
    Found by: call frame info
 3  ntdll.dll!KiUserExceptionDispatch + 0x2d
    Found by: call frame info
 4  ntdll.dll!LdrpDispatchUserCallTarget + 0xd
    Found by: call frame info
 5  MMDevAPI.dll!virtual long CDeviceEnumerator::OnDeviceStateChanged(unsigned short const *,unsigned long) + 0xef
    Found by: call frame info
 6  MMDevAPI.dll!CLocalEndpointEnumerator::OnMediaNotification + 0x31c
    Found by: call frame info
 7  MMDevAPI.dll!void CMediaNotifications::OnMediaNotificationWorkerHandler(struct _TP_CALLBACK_INSTANCE *) + 0x1f3
    Found by: call frame info
 8  ntdll.dll!TppSimplepExecuteCallback + 0x98
    Found by: call frame info
 9  ntdll.dll!TppWorkerThread + 0x689
    Found by: call frame info
10  kernel32.dll!BaseThreadInitThunk + 0x13
    Found by: call frame info
11  mozglue.dll!patched_BaseThreadInitThunk(int, void*, void*) [WindowsDllBlocklist.cpp:1c7f7adc90e2b4c8d64548938bb1499033c5be8f : 576 + 0x14]
    Found by: call frame info
12  ntdll.dll!RtlUserThreadStart + 0x20
    Found by: call frame info
```
Bam! Full stack! So, your changes are doing the right thing for `RtlDispatchException` but they are somehow regressing `KiUserExceptionDispatch`. If it helps the file this is generated from is [this one](https://msdl.microsoft.com/download/symbols/ntdll.dll/1BE73AA81F5000/ntdll.dll) and the associated PDB is [this one](https://msdl.microsoft.com/download/symbols/ntdll.pdb/75F14E124F6F8595B922D69F10C037891/ntdll.pdb).

**Comment by Swatinem** [comment]
Oh, looks like I had a very hard to spot typo in there, lol. (notice the missing `.` for cfa here: `.ra: cfa 48`; well, I didn’t until now)

Lets try now ;-)

**Comment by gabrielesvelto** [comment]
> Oh, looks like I had a very hard to spot typo in there, lol. (notice the missing `.` for cfa here: `.ra: cfa 48`; well, I didn’t until now)
> 
> Lets try now ;-)

It's working fine! There's differences in the contents of other registers but the stack trace is exactly what it's supposed to be. If I have some time I'll compare the register contents with what Visual Studio gets but in the meantime this looks ready to land.

**Review by loewenheim — APPROVED** [review]

**Comment by jrmuizel** [comment]
Do you have a plans to do a release that include this change soon?

**Comment by Swatinem** [comment]
Sorry for the delay, we had some automation issues. Anyhow, we managed to release `8.7.3`.

**Comment by gabrielesvelto** [comment]
Thanks!

**Pull request merged**
